apiVersion: installation.mattermost.com/v1beta1
kind: Mattermost
metadata:
  name: mattermost        # Example: mm-example-full
spec:
  size: 1000               # Example: 5000users
  ingress:
    enabled: true
    host: team.viduli.dev      # Example: example.mattermost-example.com
    annotations:
      kubernetes.io/ingress.class: nginx
  database:
    external:
      secret: mattermost-db-credentials
  fileStore:
    external:
      url: http://minio:9000
      bucket: mattermost
      secret: minio-credentials
  minioOperator:
    enabled: false
  version: 11.0.4              # Example: 9.3.0
  licenseSecret: ""                     # If you created a license secret, put the name here