apiVersion: batch/v1
kind: Job
metadata:
  name: minio-create-bucket
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: mc
          image: quay.io/minio/mc:RELEASE.2024-09-01T00-00-00Z
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: miniO-credentials
                  key: accesskey
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: miniO-credentials
                  key: secretkey
          command:
            - /bin/sh
            - -c
            - |
              set -e
              mc alias set local http://minio:9000 "$MINIO_ROOT_USER" "$MINIO_ROOT_PASSWORD"
              mc mb -p local/mattermost || true
              mc anonymous set download local/mattermost || true

