apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-pv
  labels:
    app: minio
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/minio

